version: '2'
services:

    kokserek:

        build: ./kokserek
        volumes:
        - ./kokserek:/usr/src/app
        depends_on:
          - postgres
        expose:
          - "8000"
        command: gunicorn kokserek.wsgi -b 0.0.0.0:8000
        env_file: ./.env

    postgres:

        image: postgres:latest
        restart: unless-stopped
        expose:
            - "5432"

        env_file: ./.env  # not needed if you have it set in your project/settings.py

        volumes:
            - pgdata:/var/lib/postgresql/data/  # persist container's db data to local pgdata/ (mounted)

    nginx:
        restart: always
        build: ./nginx/
        ports:
          - "8000:80"
        links:
          - kokserek

volumes:
  pgdata:
