version: '3.5'
services:

    kokserek:
        build: ./kokserek
        volumes:
          - .:/usr/src/app
          - ./kokserek/staticfiles:/usr/src/app/staticfiles
        depends_on:
          - postgres
        expose:
          - "8000"
        command: bash -c "cd /usr/src/app/kokserek && ./manage.py migrate && ./manage.py collectstatic --noinput &&  gunicorn kokserek.wsgi -b 0.0.0.0:8000"
        env_file: .env

    postgres:
        image: postgres:latest
        restart: unless-stopped
        env_file: .env
        volumes:
            - pgdata:/var/lib/postgresql/data

    nginx:
        restart: always
        command: bash -c "service nginx start && tail -f /dev/null"
        build:
            context: ./nginx/
        ports:
          - "80:80"
        depends_on:
          - kokserek
        volumes:
          - ./nginx/default.conf:/etc/nginx/sites-available/default
          - ./kokserek/staticfiles:/data/django/static
volumes:
    pgdata:
